embedder:
  name: 'GOOGLE' # GOOGLE or ELMO
  size: 'Small' # For ELMO : Small, Medium or Big
network:
  name: 'CNN' # CNN or BILSTM
  hidden_size: 256 # CNN : hidden layer size | BILSTM : LSTM size
  num_layers: 1 # Just for BiLSTM
  n_classes: 4 # Output size (number of classes to predict)
training:
  batch_size: 8
  shuffle: True
  n_epoch: 30
optimizer:
  learning_rate: 0.001